# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9610ff118cea4424f7fafc7aa1de6985cfd142457bd7132ce64f32bb1c7cc41d6a74625b37d984b093658a19986b5429b19598ad927eab02d7b4a47524e5aa3

test:
  secret_key_base: 06227cbf59e43fda9239fc66d92308bc48a0b939a28f29fc1266ac309f1eb2eb5eb0db717f315348ae8aaaa58644f10051b4b3f826227666c10a3504d691cc44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
